### PR TITLE
Add micro-loans features

### PR DESCRIPTION
**Pull request by Jabul99**
Pair programming with Damian, Thomas and Kim.

Requirements covered:
- FR6.1 The system should allow verified users to offer micro-loans to other customers
- FR7.1 The system should allow verified users to display their offered micro-loans
- FR8.1 The system should allow users to search for micro-loan offers
- FR9.1 The system should allow verified users to accept micro-loan offers (FR9.1.1 to FR9.1.7 only)

### CODE REVIEW

**Comment by Rubberduck1** [comment]
It was a nice pair programming session. Thanks @kimoshinowo and @Jabul99.

**Review by andehbrown — APPROVED** [review]
Nice job @kimoshinowo @Rubberduck1 @Jabul99 - all tests passed. Approved!

**Comment by Rubberduck1** [comment]
You are welcome @andehbrown

**Comment by Rubberduck1** [comment]
@andehbrown Hi Andy, I saw that you deleted our branch yesterday after the merge. Please do not delete any more branches in the future, otherwise the associated work and commits will also disappear. I think I was able to restore it.

**Pull request merged**
